#!/usr/bin/env ruby
require 'openstack'
require 'slop'
require 'ruby-progressbar'
require 'parallel'

opts = Slop.parse(strict: true, help: true) do
  banner 'Usage: populate_dummy_container [options]'
  on :u, :user=, 'Rackspace user to use', required: true
  on :k, :key=, 'Rackspace API Key', required: true
  on :s, :src=, 'Rackspace source container', default: 'database_backups'
  on :d, :dest=, 'Rackspace destination container', default: 'dummy_container'
end

def create_connection(opts)
  OpenStack::Connection.create(
      username: opts[:user],
      api_key: opts[:key],
      auth_url: 'https://identity.api.rackspacecloud.com/v1.0',
      service_type: 'object-store'
  )
end

connection = create_connection(opts)
dest_container = connection.container(opts[:dest])
src_container = connection.container(opts[:src])

objects = src_container.objects - dest_container.objects

progress = ProgressBar.create(title: 'Object names copied',
                              total: objects.size,
                              format: '%e %a |%b>%i| %p%% %t'
)
Parallel.each(objects,
              {
                  in_processes: 32,
                  finish: lambda { |_, _| progress.increment }
              }
) do |object|
  connection = create_connection(opts)
  dest_container = connection.container(opts[:dest])
  dest_container.create_object(object)
end

progress.finish
